on: 
  push:
    branches:
      - main

jobs:

  build:
      runs-on: ubuntu-latest
      steps: 
        - name: Check out code
          uses: actions/checkout@v2
        - name: Set up Python on our runner
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
              cd function
              python -m pip install --upgrade pip
              if  [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
        - name: Create zip bundle
          run: |
              cd function
              zip -r ../${{github.sha}}.zip .
        - name: Archive Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: zipped-bundle
            path: ${{github.sha }}.zip
            
  lambda1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
      - name: Lambda
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && \
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }} && \
          aws configure set region us-east-1 && \
          aws configure set output json && \
          aws lambda invoke --function-name my-func-2 --payload '{"X": -1, "Y": 2, "Z": -1}' out && cat out
  lambda2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
      - name: Lambda
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && \
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }} && \
          aws configure set region us-east-1 && \
          aws configure set output json && \
          aws lambda invoke --function-name my-func-2 --payload '{"X": -1, "Y": 0, "Z": -1}' out && cat out
